# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
  - 2.11.12
  - 2.12.5
jdk:
  - oraclejdk8
script:
  sbt ++$TRAVIS_SCALA_VERSION ";core/test;core-io/test;docker/test;docker-io/test"
